import { vars } from '~/theme'

export const styles = {
  // -- Filter bar --
  'mod-bar': {
    display: 'flex',
    alignItems: 'center',
    borderBottom: `1px solid ${vars.border}`,
    bgcolor: vars.surface,
  },
  'game-selector-btn': {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    px: '18px',
    height: 44,
    fontSize: 13,
    fontWeight: 600,
    color: vars.text,
    cursor: 'pointer',
    transition: 'background 0.15s',
    bgcolor: 'transparent',
    border: 'none',
    fontFamily: vars.ui,
    whiteSpace: 'nowrap',
    borderRight: `1px solid ${vars.border}`,
    '&:hover': { bgcolor: 'rgba(255,255,255,0.03)' },
  },
  'gs-dot': {
    width: 8,
    height: 8,
    borderRadius: '50%',
    flexShrink: 0,
  },
  'gs-dot--active': {
    bgcolor: vars.accent,
    boxShadow: `0 0 6px ${vars.accent}`,
  },
  'gs-chevron': {
    color: vars.text3,
    fontSize: 10,
    ml: '4px',
  },
  'mod-tabs': {
    display: 'flex',
    alignItems: 'stretch',
    flex: 1,
    px: '8px',
  },
  'mod-tab': {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    px: '14px',
    height: 44,
    whiteSpace: 'nowrap',
    fontSize: 13,
    fontWeight: 600,
    color: vars.text3,
    cursor: 'pointer',
    borderBottom: '2px solid transparent',
    transition: 'all 0.15s',
    '&:hover': { color: vars.text2 },
  },
  'mod-tab--active': {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    px: '14px',
    height: 44,
    whiteSpace: 'nowrap',
    fontSize: 13,
    fontWeight: 600,
    color: vars.text,
    cursor: 'pointer',
    borderBottom: `2px solid ${vars.accent}`,
    transition: 'all 0.15s',
  },
  'tab-count': {
    fontFamily: vars.mono,
    fontSize: 9,
    bgcolor: 'rgba(255,255,255,0.05)',
    border: `1px solid ${vars.border}`,
    py: '1px',
    px: '5px',
    borderRadius: '3px',
    color: vars.text3,
  },
  'tab-count--active': {
    fontFamily: vars.mono,
    fontSize: 9,
    bgcolor: vars.accLo,
    border: `1px solid ${vars.accMed}`,
    py: '1px',
    px: '5px',
    borderRadius: '3px',
    color: vars.accent,
  },
  'mod-bar-right': {
    px: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexShrink: 0,
    borderLeft: `1px solid ${vars.border}`,
  },
  'sort-btn': {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    py: '5px',
    px: '10px',
    borderRadius: '5px',
    fontSize: 12,
    fontWeight: 600,
    color: vars.text2,
    bgcolor: 'transparent',
    border: `1px solid ${vars.border}`,
    cursor: 'pointer',
    fontFamily: vars.ui,
    whiteSpace: 'nowrap',
    transition: 'all 0.15s',
    '&:hover': { borderColor: vars.borderHi, color: vars.text },
  },

  // -- Section headers --
  'section-row': {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    mb: '16px',
  },
  'section-hl': {
    fontFamily: vars.ts,
    fontSize: 18,
    letterSpacing: '0.05em',
    lineHeight: 1,
  },
  'section-sub': {
    fontFamily: vars.mono,
    fontSize: 9,
    color: vars.text3,
    mt: '3px',
    letterSpacing: '0.06em',
  },
  'see-all': {
    fontSize: 12,
    color: vars.accent,
    fontWeight: 600,
    cursor: 'pointer',
    '&:hover': { textDecoration: 'underline' },
  },

  // -- Mod Grid --
  'mod-grid-wrap': {
    p: '24px 24px 48px',
  },
  'mods-grid': {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
    gap: '14px',
    mb: '40px',
  },
  'mods-grid--six': {
    display: 'grid',
    gridTemplateColumns: 'repeat(6, 1fr)',
    gap: '14px',
    mb: '40px',
  },
}
