import { vars } from '~/theme'

export const styles = {
  'kanban-board': {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    overflow: 'hidden',
    minWidth: 0,
  },

  // Topbar
  'kanban-board__topbar': {
    display: 'flex',
    alignItems: 'center',
    height: 52,
    borderBottom: `1px solid ${vars.border}`,
    flexShrink: 0,
    px: '24px',
    gap: '12px',
    bgcolor: vars.bg,
  },
  'kanban-board__breadcrumb': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: 13,
    color: vars.text2,
  },
  'kanban-board__bc-sep': {
    color: vars.text3,
  },
  'kanban-board__bc-item': {
    fontSize: 'inherit',
    color: 'inherit',
  },
  'kanban-board__bc-active': {
    color: vars.text,
    fontWeight: 600,
  },
  'kanban-board__filters': {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    ml: '24px',
  },
  'kanban-board__tab': {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    py: '4px',
    px: '10px',
    borderRadius: '5px',
    fontSize: 11,
    fontWeight: 600,
    color: vars.text2,
    bgcolor: 'transparent',
    border: `1px solid ${vars.border}`,
    cursor: 'pointer',
    fontFamily: vars.ui,
    transition: 'all 0.12s',
    '&:hover': { borderColor: vars.borderHi, color: vars.text },
  },
  'kanban-board__tab--active': {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    py: '4px',
    px: '10px',
    borderRadius: '5px',
    fontSize: 11,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: vars.ui,
    transition: 'all 0.12s',
  },
  'kanban-board__filter-sep': {
    width: '1px',
    height: 18,
    bgcolor: vars.border,
    mx: '4px',
  },
  'kanban-board__archived-toggle': {
    display: 'flex',
    alignItems: 'center',
    gap: '7px',
    fontSize: 12,
    color: vars.text3,
    cursor: 'pointer',
    py: '4px',
    px: '10px',
    borderRadius: '5px',
    border: `1px solid ${vars.border}`,
    transition: 'all 0.12s',
    '&:hover': { borderColor: vars.borderHi, color: vars.text2 },
  },
  'kanban-board__toggle-track': {
    width: 26,
    height: 14,
    borderRadius: 99,
    bgcolor: 'rgba(255,255,255,0.1)',
    position: 'relative',
    flexShrink: 0,
    transition: 'background 0.15s',
  },
  'kanban-board__toggle-track--on': {
    width: 26,
    height: 14,
    borderRadius: 99,
    bgcolor: vars.accent,
    position: 'relative',
    flexShrink: 0,
    transition: 'background 0.15s',
  },
  'kanban-board__toggle-thumb': {
    width: 10,
    height: 10,
    borderRadius: '50%',
    bgcolor: '#fff',
    position: 'absolute',
    top: 2,
    left: 2,
    transition: 'transform 0.15s',
  },
  'kanban-board__toggle-thumb--on': {
    width: 10,
    height: 10,
    borderRadius: '50%',
    bgcolor: '#fff',
    position: 'absolute',
    top: 2,
    left: 2,
    transition: 'transform 0.15s',
    transform: 'translateX(12px)',
  },
  'kanban-board__archived-num': {
    fontFamily: vars.mono,
    fontSize: 9,
    bgcolor: 'rgba(255,255,255,0.06)',
    border: `1px solid ${vars.border}`,
    py: '1px',
    px: '5px',
    borderRadius: '3px',
  },
  'kanban-board__topbar-right': {
    ml: 'auto',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  'kanban-board__btn-accent': {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    py: '6px',
    px: '14px',
    borderRadius: '6px',
    fontSize: 12,
    fontWeight: 700,
    fontFamily: vars.ui,
    cursor: 'pointer',
    transition: 'all 0.15s',
    bgcolor: vars.accent,
    border: 'none',
    color: '#000',
    '&:hover': { bgcolor: vars.accentHover, boxShadow: `0 0 20px ${vars.accGlow}` },
  },

  // Board
  'kanban-board__board': {
    flex: 1,
    overflowX: 'auto',
    overflowY: 'hidden',
    p: '16px 20px',
    display: 'flex',
    gap: '12px',
  },
}
