import { vars } from '~/theme'

export const styles = {
  'forge-layout': {
    display: 'grid',
    gridTemplateColumns: '220px 1fr',
    minHeight: 'calc(100vh - 52px)',
  },

  // -- Sidebar --
  'forge-sidebar': {
    bgcolor: vars.surface,
    borderRight: `1px solid ${vars.border}`,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  'fsb-project': {
    p: '14px 16px',
    borderBottom: `1px solid ${vars.border}`,
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    cursor: 'pointer',
    transition: 'background 0.15s',
    '&:hover': { bgcolor: 'rgba(255,255,255,0.02)' },
  },
  'fsb-proj-img': {
    width: 34,
    height: 34,
    borderRadius: '7px',
    flexShrink: 0,
    background: 'linear-gradient(135deg, #1a2e1a, #0d1a0d)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 15,
    border: `1px solid ${vars.borderHi}`,
  },
  'fsb-proj-name': {
    fontSize: 12,
    fontWeight: 700,
    color: vars.text,
    mb: '2px',
  },
  'fsb-proj-sub': {
    fontFamily: vars.mono,
    fontSize: 9,
    color: vars.accent,
  },
  'fsb-chevron': {
    ml: 'auto',
    color: vars.text3,
    fontSize: 11,
  },
  'fsb-nav': {
    p: '10px 8px',
    flex: 1,
    overflowY: 'auto',
  },
  'fsb-label': {
    fontFamily: vars.mono,
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: '0.14em',
    color: vars.text3,
    p: '6px 10px 8px',
  },
  'fsb-item': {
    display: 'flex',
    alignItems: 'center',
    gap: '9px',
    py: '7px',
    px: '10px',
    borderRadius: '6px',
    mb: '1px',
    fontSize: 13,
    fontWeight: 500,
    color: vars.text2,
    cursor: 'pointer',
    transition: 'all 0.12s',
    '&:hover': { bgcolor: 'rgba(255,255,255,0.03)', color: vars.text },
  },
  'fsb-item--active': {
    display: 'flex',
    alignItems: 'center',
    gap: '9px',
    py: '7px',
    px: '10px',
    borderRadius: '6px',
    mb: '1px',
    fontSize: 13,
    fontWeight: 500,
    color: vars.text,
    cursor: 'pointer',
    transition: 'all 0.12s',
    bgcolor: vars.accLo,
  },
  'fsb-icon': {
    fontSize: 14,
    width: 16,
    textAlign: 'center',
    flexShrink: 0,
    opacity: 0.7,
  },
  'fsb-icon--active': {
    fontSize: 14,
    width: 16,
    textAlign: 'center',
    flexShrink: 0,
    color: vars.accent,
  },
  'fsb-chip': {
    ml: 'auto',
    fontFamily: vars.mono,
    fontSize: 9,
    py: '1px',
    px: '5px',
    borderRadius: '3px',
  },
  'chip-acc': {
    bgcolor: vars.accLo,
    border: `1px solid ${vars.accMed}`,
    color: vars.accent,
  },
  'chip-def': {
    bgcolor: 'rgba(255,255,255,0.05)',
    border: `1px solid ${vars.border}`,
    color: vars.text3,
  },
  'fsb-divider': {
    height: '1px',
    bgcolor: vars.border,
    my: '8px',
  },
  'fsb-footer': {
    borderTop: `1px solid ${vars.border}`,
    p: '12px 8px',
  },
  'fsb-user': {
    display: 'flex',
    alignItems: 'center',
    gap: '9px',
    py: '7px',
    px: '10px',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'background 0.12s',
    '&:hover': { bgcolor: 'rgba(255,255,255,0.03)' },
  },
  'fsb-uav': {
    width: 28,
    height: 28,
    borderRadius: '7px',
    background: `linear-gradient(135deg, ${vars.accent}, #dc2626)`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 11,
    fontWeight: 700,
    color: '#fff',
    flexShrink: 0,
  },
  'fsb-uname': {
    fontSize: 12,
    fontWeight: 600,
    color: vars.text,
  },
  'fsb-usub': {
    fontSize: 10,
    color: vars.text3,
  },

  // -- Forge main --
  'forge-main': {
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
  },

  // -- Topbar --
  'forge-topbar': {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    px: '28px',
    height: 52,
    borderBottom: `1px solid ${vars.border}`,
    bgcolor: vars.bg,
    flexShrink: 0,
  },
  'ftb-crumb': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: 13,
    color: vars.text2,
  },
  'ftb-sep': { color: vars.text3 },
  'ftb-active': { color: vars.text, fontWeight: 600 },
  'ftb-right': {
    ml: 'auto',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },

  // -- Buttons --
  'btn-accent': {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    py: '6px',
    px: '14px',
    borderRadius: '3px',
    fontSize: 13,
    fontWeight: 700,
    fontFamily: vars.ui,
    cursor: 'pointer',
    transition: 'all 0.15s',
    border: 'none',
    bgcolor: vars.accent,
    color: '#000',
    '&:hover': { bgcolor: vars.accentHover, boxShadow: `0 4px 20px ${vars.accGlow}` },
  },
  'sm-btn': {
    py: '5px',
    px: '11px',
    borderRadius: '5px',
    fontSize: 11,
    fontWeight: 600,
    cursor: 'pointer',
    border: `1px solid ${vars.borderHi}`,
    bgcolor: 'transparent',
    color: vars.text2,
    fontFamily: vars.ui,
    transition: 'all 0.12s',
    '&:hover': { bgcolor: 'rgba(255,255,255,0.04)', color: vars.text },
  },

  // -- Metrics strip --
  'metric-strip': {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    borderBottom: `1px solid ${vars.border}`,
    flexShrink: 0,
  },
  'metric-cell': {
    p: '18px 24px',
    borderRight: `1px solid ${vars.border}`,
    cursor: 'default',
    transition: 'background 0.15s',
    '&:last-child': { borderRight: 'none' },
    '&:hover': { bgcolor: 'rgba(255,255,255,0.012)' },
  },
  'metric-label': {
    fontFamily: vars.mono,
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    color: vars.text2,
    mb: '6px',
  },
  'metric-num': {
    fontFamily: vars.ts,
    fontSize: 36,
    letterSpacing: '0.03em',
    lineHeight: 1,
    color: vars.text,
    mb: '5px',
  },
  'metric-num--red': { color: vars.red },
  'metric-num--green': { color: vars.green },
  'metric-num--accent': { color: vars.accent },
  'metric-delta': {
    fontFamily: vars.mono,
    fontSize: 12,
    color: vars.green,
  },
  'metric-delta--neg': {
    fontFamily: vars.mono,
    fontSize: 12,
    color: vars.red,
  },
  'metric-delta--neu': {
    fontFamily: vars.mono,
    fontSize: 12,
    color: vars.text2,
  },

  // -- Forge content --
  'forge-content': {
    display: 'grid',
    gridTemplateColumns: '1fr 280px',
    flex: 1,
    minHeight: 0,
  },

  // -- Project list --
  'proj-col': {
    p: '24px 28px',
    borderRight: `1px solid ${vars.border}`,
    overflowY: 'auto',
  },
  'proj-col-head': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    mb: '14px',
  },
  'proj-col-title': {
    fontSize: 12,
    fontWeight: 700,
    color: vars.text,
    display: 'flex',
    alignItems: 'center',
    gap: '7px',
  },
  'proj-count': {
    fontFamily: vars.mono,
    fontSize: 9,
    bgcolor: 'rgba(255,255,255,0.05)',
    border: `1px solid ${vars.border}`,
    py: '1px',
    px: '5px',
    borderRadius: '3px',
    color: vars.text3,
  },
  'filter-pills': {
    display: 'flex',
    gap: '4px',
    mb: '16px',
  },
  'fpill': {
    py: '4px',
    px: '11px',
    borderRadius: '5px',
    fontSize: 11,
    fontWeight: 600,
    cursor: 'pointer',
    border: `1px solid ${vars.border}`,
    bgcolor: 'transparent',
    color: vars.text3,
    fontFamily: vars.ui,
    transition: 'all 0.12s',
    '&:hover': { color: vars.text2, borderColor: vars.borderHi },
  },
  'fpill--active': {
    py: '4px',
    px: '11px',
    borderRadius: '5px',
    fontSize: 11,
    fontWeight: 600,
    cursor: 'pointer',
    bgcolor: vars.accLo,
    color: vars.accent,
    border: `1px solid ${vars.accMed}`,
    fontFamily: vars.ui,
    transition: 'all 0.12s',
  },
  'proj-list': {
    display: 'flex',
    flexDirection: 'column',
    gap: '7px',
  },

  // -- Right panel (activity) --
  'right-panel': {
    p: '20px 18px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    overflowY: 'auto',
  },
  'widget-hl': {
    fontFamily: vars.mono,
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: '0.14em',
    color: vars.text3,
    mb: '11px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  'widget-link': {
    color: vars.text3,
    cursor: 'pointer',
    transition: 'color 0.12s',
    '&:hover': { color: vars.accent },
  },
  'act-item': {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '9px',
    py: '9px',
    borderBottom: `1px solid ${vars.border}`,
    '&:last-child': { borderBottom: 'none' },
  },
  'act-dot': {
    width: 6,
    height: 6,
    borderRadius: '50%',
    flexShrink: 0,
    mt: '5px',
  },
  'd-r': { bgcolor: vars.red },
  'd-o': { bgcolor: vars.accent },
  'd-g': { bgcolor: vars.green },
  'd-b': { bgcolor: vars.blue },
  'act-txt': {
    fontSize: 12,
    color: vars.text2,
    lineHeight: 1.45,
    fontWeight: 300,
  },
  'act-time': {
    fontFamily: vars.mono,
    fontSize: 9,
    color: vars.text3,
    mt: '2px',
  },
}
