import { vars } from '~/theme'

export const styles = {
  'kanban-card': {
    bgcolor: vars.card,
    border: `1px solid ${vars.border}`,
    borderRadius: '9px',
    p: '12px 14px',
    mb: '8px',
    cursor: 'pointer',
    transition: 'all 0.15s',
    position: 'relative',
    '&:hover': {
      bgcolor: vars.cardHi,
      borderColor: vars.borderHi,
      transform: 'translateY(-1px)',
      boxShadow: '0 6px 24px rgba(0,0,0,0.35)',
    },
    '&:hover .card-menu-btn': { opacity: 1 },
  },
  'kanban-card__accent': {
    position: 'absolute',
    left: 0,
    top: 8,
    bottom: 8,
    width: 2,
    borderRadius: '0 2px 2px 0',
  },
  'kanban-card__top': {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '8px',
    mb: '8px',
  },
  'kanban-card__title': {
    fontSize: 12,
    fontWeight: 600,
    color: vars.text,
    lineHeight: 1.5,
    flex: 1,
  },
  'kanban-card__menu': {
    width: 20,
    height: 20,
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    color: vars.text3,
    cursor: 'pointer',
    flexShrink: 0,
    transition: 'all 0.12s',
    opacity: 0,
    bgcolor: 'transparent',
    border: 'none',
    '&:hover': { bgcolor: 'rgba(255,255,255,0.06)', color: vars.text2 },
  },
  'kanban-card__tags': {
    display: 'flex',
    gap: '5px',
    flexWrap: 'wrap',
    mb: '10px',
  },
  'kanban-card__tag': {
    fontFamily: vars.mono,
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    py: '2px',
    px: '6px',
    borderRadius: '3px',
  },
  'kanban-card__footer': {
    display: 'flex',
    alignItems: 'center',
    borderTop: `1px solid ${vars.border}`,
    pt: '8px',
  },
  'kanban-card__priority-badge': {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontFamily: vars.mono,
    fontSize: 10,
    py: '2px',
    px: '7px',
    borderRadius: '3px',
    mr: '6px',
  },
  'kanban-card__priority-icon': {
    width: 14,
    height: 14,
    flexShrink: 0,
  },
  'kanban-card__version': {
    fontFamily: vars.mono,
    fontSize: 11,
    color: vars.text2,
    mr: 'auto',
  },
  'kanban-card__category': {
    fontFamily: vars.mono,
    fontSize: 10,
    py: '1px',
    px: '5px',
    borderRadius: '3px',
    bgcolor: 'rgba(255,255,255,0.04)',
    border: `1px solid ${vars.border}`,
    color: vars.text2,
    mr: '6px',
  },
  'kanban-card__author': {
    width: 20,
    height: 20,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 8,
    fontWeight: 700,
    color: '#fff',
    border: `1px solid ${vars.bg}`,
    cursor: 'pointer',
    transition: 'transform 0.12s',
    ml: '10px',
    '&:hover': { transform: 'scale(1.15)' },
  },
  'kanban-card__upvote': {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontFamily: vars.mono,
    fontSize: 11,
    color: vars.blue,
    bgcolor: 'rgba(59,130,246,0.08)',
    border: '1px solid rgba(59,130,246,0.25)',
    borderRadius: '4px',
    py: '2px',
    px: '7px',
    cursor: 'pointer',
    transition: 'all 0.15s',
    ml: '6px',
    flexShrink: 0,
    '&:hover': {
      color: '#93c5fd',
      bgcolor: 'rgba(59,130,246,0.15)',
      borderColor: 'rgba(59,130,246,0.4)',
    },
  },
  'kanban-card__delete': { color: vars.red },
}
