import { vars } from '~/theme'

export const styles = {
  'landing': {
    minHeight: '100vh',
    bgcolor: vars.bg,
    color: vars.text,
    fontFamily: vars.ui,
    fontSize: 14,
    WebkitFontSmoothing: 'antialiased',
  },

  'landing__body': {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '20px',
    p: '48px 28px',
    minHeight: 'calc(100vh - 52px)',
  },

  'landing__card': {
    width: 420,
    borderRadius: '14px',
    border: `1px solid ${vars.border}`,
    bgcolor: vars.card,
    p: '40px 36px',
    cursor: 'pointer',
    transition: 'all 0.22s',
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  'landing__card--mod': {
    '&:hover': {
      transform: 'translateY(-4px)',
      borderColor: 'rgba(59,130,246,0.3)',
      boxShadow: '0 16px 48px rgba(0,0,0,0.5), 0 0 0 1px rgba(59,130,246,0.1)',
    },
    '&::before': {
      content: '""',
      position: 'absolute',
      inset: 0,
      background: 'radial-gradient(ellipse at 30% 0%, rgba(59,130,246,0.08), transparent 70%)',
      opacity: 0,
      transition: 'opacity 0.22s',
      pointerEvents: 'none',
    },
    '&:hover::before': { opacity: 1 },
  },
  'landing__card--forge': {
    '&:hover': {
      transform: 'translateY(-4px)',
      borderColor: 'rgba(249,115,22,0.3)',
      boxShadow: '0 16px 48px rgba(0,0,0,0.5), 0 0 0 1px rgba(249,115,22,0.1)',
    },
    '&::before': {
      content: '""',
      position: 'absolute',
      inset: 0,
      background: 'radial-gradient(ellipse at 30% 0%, rgba(249,115,22,0.1), transparent 70%)',
      opacity: 0,
      transition: 'opacity 0.22s',
      pointerEvents: 'none',
    },
    '&:hover::before': { opacity: 1 },
  },
  'landing__card-icon': {
    fontSize: 32,
    mb: '20px',
    width: 56,
    height: 56,
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 1,
  },
  'landing__card-icon--mod': {
    bgcolor: 'rgba(59,130,246,0.1)',
    border: '1px solid rgba(59,130,246,0.2)',
  },
  'landing__card-icon--forge': {
    bgcolor: vars.accLo,
    border: '1px solid rgba(249,115,22,0.2)',
  },
  'landing__card-title': {
    fontFamily: vars.ts,
    fontSize: 28,
    letterSpacing: '0.04em',
    lineHeight: 1,
    color: vars.text,
    mb: '10px',
    position: 'relative',
    zIndex: 1,
  },
  'landing__card-title--mod-accent': {
    fontStyle: 'normal',
    color: vars.modBlue,
  },
  'landing__card-title--forge-accent': {
    fontStyle: 'normal',
    color: vars.accent,
  },
  'landing__card-subtitle': {
    fontSize: 13,
    fontWeight: 300,
    color: vars.text2,
    lineHeight: 1.6,
    mb: '28px',
    position: 'relative',
    zIndex: 1,
  },
  'landing__card-features': {
    display: 'flex',
    flexDirection: 'column',
    gap: '7px',
    mb: '28px',
    position: 'relative',
    zIndex: 1,
  },
  'landing__feature': {
    display: 'flex',
    alignItems: 'center',
    gap: '9px',
    fontSize: 12,
    color: vars.text2,
    fontWeight: 400,
  },
  'landing__feature-dot': {
    width: 5,
    height: 5,
    borderRadius: '50%',
    flexShrink: 0,
  },
  'landing__feature-dot--mod': { bgcolor: vars.modBlue },
  'landing__feature-dot--forge': { bgcolor: vars.accent },
  'landing__card-cta': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    py: '12px',
    px: '16px',
    borderRadius: '8px',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    border: 'none',
    fontFamily: vars.ui,
    transition: 'all 0.15s',
    position: 'relative',
    zIndex: 1,
  },
  'landing__card-cta--mod': {
    bgcolor: vars.modBg,
    color: vars.modBlue,
  },
  'landing__card-cta--forge': {
    bgcolor: 'rgba(249,115,22,0.15)',
    color: vars.accent,
  },
  'landing__cta-arrow': {
    fontSize: 16,
    transition: 'transform 0.15s',
  },
  'landing__divider': {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    color: vars.text3,
    fontSize: 12,
    fontWeight: 500,
    flexShrink: 0,
  },
  'landing__divider-line': {
    width: '1px',
    height: 60,
    bgcolor: vars.border,
  },
}
