import { vars } from '~/theme'

export const styles = {
  // -- Layout --
  'pp': {
    display: 'grid',
    gridTemplateColumns: '1fr 300px',
    flex: 1,
    minHeight: 0,
    position: 'relative',
    zIndex: 1,
  },
  'pp__left': {
    p: '24px 28px',
    borderRight: `1px solid ${vars.border}`,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '28px',
  },
  'pp__right': {
    p: '20px 18px',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    overflowY: 'auto',
  },

  // -- Hero card --
  'hero': {
    bgcolor: vars.card,
    border: `1px solid ${vars.border}`,
    borderRadius: '12px',
    overflow: 'hidden',
  },
  'hero__banner': {
    height: 140,
    position: 'relative',
    overflow: 'hidden',
    background: 'linear-gradient(140deg, #0f1a2e 0%, #1a1000 50%, #0a0a0e 100%)',
  },
  'hero__banner-img': {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  'hero__banner-glow': {
    position: 'absolute',
    inset: 0,
    background: `radial-gradient(ellipse at 30% 60%, rgba(249,115,22,0.18), transparent 60%), radial-gradient(ellipse at 70% 30%, rgba(59,130,246,0.12), transparent 50%)`,
  },
  'hero__banner-accent': {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '2px',
    background: `linear-gradient(90deg, ${vars.accent}, transparent)`,
  },
  'hero__body': {
    p: '20px 24px 24px',
  },

  // Title row
  'hero__title-row': {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '14px',
    mb: '10px',
  },
  'hero__avatar': {
    width: 52,
    height: 52,
    borderRadius: '10px',
    border: `2px solid ${vars.borderHi}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 22,
    flexShrink: 0,
    mt: '-38px',
    position: 'relative',
    zIndex: 2,
    boxShadow: '0 4px 16px rgba(0,0,0,0.5)',
    overflow: 'hidden',
    bgcolor: vars.surface,
  },
  'hero__avatar-img': {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  'hero__title-info': {
    flex: 1,
    pt: '4px',
  },
  'hero__name': {
    fontFamily: vars.ts,
    fontSize: 26,
    letterSpacing: '0.04em',
    color: vars.text,
    lineHeight: 1,
    mb: '6px',
  },
  'hero__meta-row': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
  },
  'hero__ver-badge': {
    fontFamily: vars.mono,
    fontSize: 10,
    bgcolor: 'rgba(249,115,22,0.15)',
    border: `1px solid ${vars.accMed}`,
    color: vars.accent,
    py: '2px',
    px: '8px',
    borderRadius: '4px',
    fontWeight: 500,
  },
  'hero__status-pill': {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    fontFamily: vars.mono,
    fontSize: 9,
    py: '2px',
    px: '8px',
    borderRadius: '4px',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  'hero__status-pill--live': {
    bgcolor: 'rgba(34,197,94,0.1)',
    border: '1px solid rgba(34,197,94,0.2)',
    color: '#4ade80',
  },
  'hero__status-dot': {
    width: 5,
    height: 5,
    borderRadius: '50%',
    bgcolor: 'currentColor',
  },
  'hero__history-btn': {
    width: 26,
    height: 26,
    borderRadius: '5px',
    bgcolor: 'transparent',
    border: `1px solid ${vars.border}`,
    color: vars.text3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: 13,
    transition: 'all 0.12s',
    ml: '2px',
    '&:hover': { borderColor: vars.borderHi, color: vars.text2 },
  },

  // Owner
  'hero__owner-row': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    mb: '16px',
  },
  'hero__owner-av': {
    width: 22,
    height: 22,
    borderRadius: '5px',
    background: 'linear-gradient(135deg, #5865f2, #4f46e5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 9,
    fontWeight: 700,
    color: '#fff',
    overflow: 'hidden',
  },
  'hero__owner-av-img': {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  'hero__owner-name': {
    fontSize: 12,
    fontWeight: 600,
    color: vars.text2,
  },

  // Description
  'hero__desc': {
    fontSize: 13,
    fontWeight: 300,
    color: vars.text2,
    lineHeight: 1.65,
    mb: '16px',
  },

  // Stats row
  'hero__stats-row': {
    display: 'flex',
    alignItems: 'center',
    gap: 0,
    pt: '14px',
    borderTop: `1px solid ${vars.border}`,
  },
  'hero__stat': {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    px: '18px',
    borderRight: `1px solid ${vars.border}`,
    fontSize: 12,
    color: vars.text2,
    '&:first-of-type': { pl: 0 },
    '&:last-of-type': { borderRight: 'none' },
  },
  'hero__stat-icon': {
    fontSize: 13,
    color: vars.text3,
  },
  'hero__stat-val': {
    fontFamily: vars.mono,
    fontSize: 11,
    color: vars.text,
    fontWeight: 500,
  },
  'hero__stat-label': {
    fontSize: 11,
    color: vars.text3,
  },

  // -- Section header --
  'section-head': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    mb: '14px',
  },
  'section-title': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: 12,
    fontWeight: 700,
    color: vars.text,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  'section-count': {
    fontFamily: vars.mono,
    fontSize: 9,
    bgcolor: 'rgba(255,255,255,0.05)',
    border: `1px solid ${vars.border}`,
    py: '1px',
    px: '6px',
    borderRadius: '3px',
    color: vars.text3,
  },
  'section-action': {
    fontSize: 11,
    fontWeight: 600,
    color: vars.accent,
    cursor: 'pointer',
    py: '3px',
    px: '8px',
    borderRadius: '4px',
    border: `1px solid ${vars.accMed}`,
    bgcolor: vars.accLo,
    transition: 'all 0.12s',
    '&:hover': { bgcolor: 'rgba(249,115,22,0.15)' },
  },

  // -- Members grid --
  'members-grid': {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '10px',
  },
  'mg': {
    bgcolor: vars.surface,
    border: `1px solid ${vars.border}`,
    borderRadius: '9px',
    p: '14px 16px',
  },
  'mg__label': {
    fontFamily: vars.mono,
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
    color: vars.text3,
    mb: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  'mg__count': {
    fontFamily: vars.mono,
    fontSize: 9,
    bgcolor: 'rgba(255,255,255,0.05)',
    border: `1px solid ${vars.border}`,
    py: '1px',
    px: '5px',
    borderRadius: '3px',
    color: vars.text3,
  },
  'mg__list': {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  'mg__row': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    py: '6px',
    px: '8px',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'background 0.12s',
    '&:hover': { bgcolor: 'rgba(255,255,255,0.03)' },
  },
  'mg__av': {
    width: 26,
    height: 26,
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 10,
    fontWeight: 700,
    color: '#fff',
    flexShrink: 0,
    overflow: 'hidden',
  },
  'mg__av-img': {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  'mg__name': {
    fontSize: 12,
    fontWeight: 500,
    color: vars.text2,
  },
  'mg__role': {
    ml: 'auto',
    fontFamily: vars.mono,
    fontSize: 8,
    py: '1px',
    px: '5px',
    borderRadius: '3px',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  'mg__role--owner': {
    bgcolor: 'rgba(249,115,22,0.1)',
    border: '1px solid rgba(249,115,22,0.2)',
    color: vars.accent,
  },
  'mg__role--maintainer': {
    bgcolor: 'rgba(59,130,246,0.1)',
    border: '1px solid rgba(59,130,246,0.2)',
    color: '#60a5fa',
  },
  'mg__role--contributor': {
    bgcolor: 'rgba(255,255,255,0.04)',
    border: `1px solid ${vars.border}`,
    color: vars.text3,
  },

  // -- Categories --
  'cats-grid': {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  'cat': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    bgcolor: vars.card,
    border: `1px solid ${vars.border}`,
    borderRadius: '8px',
    py: '8px',
    px: '14px',
    cursor: 'pointer',
    transition: 'all 0.15s',
    position: 'relative',
    overflow: 'hidden',
    '&:hover': { borderColor: vars.borderHi, bgcolor: vars.cardHi },
  },
  'cat__dot': {
    width: 7,
    height: 7,
    borderRadius: '50%',
    flexShrink: 0,
  },
  'cat__name': {
    fontSize: 12,
    fontWeight: 600,
    color: vars.text,
  },
  'cat__progress': {
    fontFamily: vars.mono,
    fontSize: 10,
    color: vars.text3,
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
  },
  'cat__bar': {
    width: 40,
    height: 3,
    bgcolor: 'rgba(255,255,255,0.06)',
    borderRadius: '2px',
    overflow: 'hidden',
  },
  'cat__fill': {
    height: '100%',
    borderRadius: '2px',
  },
  'cat__prog-line': {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '2px',
    bgcolor: 'rgba(255,255,255,0.03)',
  },
  'cat__prog-line-fill': {
    height: '100%',
    borderRadius: '0 2px 2px 0',
    opacity: 0.6,
  },

  // -- Right panel widgets --
  'widget-label': {
    fontFamily: vars.mono,
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: '0.14em',
    color: vars.text3,
    mb: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  'widget-link': {
    color: vars.text3,
    cursor: 'pointer',
    fontSize: 9,
    transition: 'color 0.12s',
    '&:hover': { color: vars.accent },
  },

  // Quick actions
  'qa': {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  'qa__btn': {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    py: '10px',
    px: '12px',
    borderRadius: '7px',
    bgcolor: vars.card,
    border: `1px solid ${vars.border}`,
    cursor: 'pointer',
    transition: 'all 0.15s',
    fontSize: 12,
    fontWeight: 600,
    color: vars.text2,
    '&:hover': { bgcolor: vars.cardHi, borderColor: vars.borderHi, color: vars.text },
  },
  'qa__btn--primary': {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    py: '10px',
    px: '12px',
    borderRadius: '7px',
    bgcolor: vars.accLo,
    border: `1px solid ${vars.accMed}`,
    cursor: 'pointer',
    transition: 'all 0.15s',
    fontSize: 12,
    fontWeight: 600,
    color: vars.accent,
    '&:hover': { bgcolor: 'rgba(249,115,22,0.18)' },
  },
  'qa__icon': {
    width: 28,
    height: 28,
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 13,
    flexShrink: 0,
  },
  'qa__icon--accent': {
    bgcolor: 'rgba(249,115,22,0.12)',
    border: '1px solid rgba(249,115,22,0.15)',
  },
  'qa__icon--default': {
    bgcolor: 'rgba(255,255,255,0.04)',
    border: `1px solid ${vars.border}`,
  },
  'qa__label': {
    flex: 1,
  },
  'qa__meta': {
    fontFamily: vars.mono,
    fontSize: 9,
    color: vars.text3,
    fontWeight: 400,
    mt: '1px',
  },
  'qa__arrow': {
    color: vars.text3,
    fontSize: 11,
    transition: 'transform 0.15s',
  },

  // Info rows
  'info-rows': {
    display: 'flex',
    flexDirection: 'column',
  },
  'info-row': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    py: '9px',
    borderBottom: `1px solid ${vars.border}`,
    fontSize: 12,
    '&:last-of-type': { borderBottom: 'none' },
  },
  'info-key': {
    color: vars.text3,
    fontWeight: 400,
  },
  'info-val': {
    color: vars.text2,
    fontWeight: 500,
    fontFamily: vars.mono,
    fontSize: 11,
  },
  'info-val--accent': {
    color: vars.accent,
  },
  'info-val--green': {
    color: vars.green,
  },

  // Activity
  'act-feed': {
    display: 'flex',
    flexDirection: 'column',
  },
  'act-row': {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '9px',
    py: '9px',
    borderBottom: `1px solid ${vars.border}`,
    '&:last-of-type': { borderBottom: 'none' },
  },
  'act-dot': {
    width: 6,
    height: 6,
    borderRadius: '50%',
    flexShrink: 0,
    mt: '5px',
  },
  'd-r': { bgcolor: vars.red },
  'd-o': { bgcolor: vars.accent },
  'd-g': { bgcolor: vars.green },
  'd-b': { bgcolor: vars.blue },
  'act-body': {
    flex: 1,
  },
  'act-text': {
    fontSize: 12,
    fontWeight: 300,
    color: vars.text2,
    lineHeight: 1.5,
  },
  'act-time': {
    fontFamily: vars.mono,
    fontSize: 9,
    color: vars.text3,
    mt: '2px',
  },
}
