import { vars } from '~/theme'

export const styles = {
  'rte': {
    display: 'flex',
    flexDirection: 'column',
  },

  // -- Toolbar --
  'rte__toolbar': {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '2px',
    p: '6px 8px',
    borderBottom: `1px solid ${vars.border}`,
    bgcolor: vars.surface,
  },
  'rte__toolbar-group': {
    display: 'flex',
    gap: '2px',
    alignItems: 'center',
    '&:not(:last-of-type)': {
      mr: '4px',
      pr: '6px',
      borderRight: `1px solid ${vars.border}`,
    },
  },
  'rte__toolbar-button': {
    width: 28,
    height: 28,
    borderRadius: '4px',
    border: 'none',
    bgcolor: 'transparent',
    color: vars.text3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: 12,
    transition: 'all 0.1s',
    '&:hover': {
      bgcolor: vars.hoverBg,
      color: vars.text2,
    },
  },
  'rte__toolbar-button--active': {
    bgcolor: vars.accLo,
    color: vars.accent,
    '&:hover': {
      bgcolor: vars.accLoHover,
      color: vars.accent,
    },
  },
  'rte__toolbar-select': {
    height: 28,
    bgcolor: 'transparent',
    border: 'none',
    color: vars.text3,
    fontSize: 11,
    fontFamily: vars.mono,
    cursor: 'pointer',
    borderRadius: '4px',
    px: '6px',
    outline: 'none',
    '&:hover': {
      bgcolor: vars.hoverBg,
      color: vars.text2,
    },
    '& option': {
      bgcolor: vars.card,
      color: vars.text,
    },
  },

  // -- Editor area --
  'rte__content': {
    minHeight: 280,
    maxHeight: 500,
    overflowY: 'auto',
    p: '14px 16px',
    fontSize: 13,
    fontWeight: 300,
    color: vars.text,
    lineHeight: 1.7,
    outline: 'none',
    cursor: 'text',
    '& h1': {
      fontSize: 22,
      fontWeight: 600,
      color: vars.text,
      mt: '4px',
      mb: '8px',
      lineHeight: 1.3,
    },
    '& h2': {
      fontSize: 18,
      fontWeight: 600,
      color: vars.text,
      mt: '4px',
      mb: '6px',
      lineHeight: 1.3,
    },
    '& h3': {
      fontSize: 15,
      fontWeight: 600,
      color: vars.text,
      mt: '4px',
      mb: '4px',
      lineHeight: 1.3,
    },
    '& p': {
      my: '2px',
    },
    '& a': {
      color: vars.accent,
      textDecoration: 'underline',
    },
    '& ul, & ol': {
      pl: '20px',
      my: '4px',
    },
    '& li': {
      my: '2px',
    },
    '& blockquote': {
      borderLeft: `3px solid ${vars.accent}`,
      pl: '12px',
      ml: '0',
      my: '8px',
      color: vars.text2,
      fontStyle: 'italic',
    },
    '& code': {
      fontFamily: vars.mono,
      fontSize: 12,
      bgcolor: 'rgba(255,255,255,0.06)',
      border: `1px solid ${vars.border}`,
      borderRadius: '3px',
      py: '1px',
      px: '4px',
    },
    '& pre': {
      fontFamily: vars.mono,
      fontSize: 12,
      bgcolor: 'rgba(255,255,255,0.04)',
      border: `1px solid ${vars.border}`,
      borderRadius: '6px',
      p: '12px',
      my: '8px',
      overflowX: 'auto',
      '& code': {
        bgcolor: 'transparent',
        border: 'none',
        p: 0,
      },
    },
    '& hr': {
      border: 'none',
      borderTop: `1px solid ${vars.border}`,
      my: '12px',
    },
    '& img': {
      maxWidth: '100%',
      borderRadius: '6px',
      my: '8px',
      display: 'block',
    },
    '& .rte-video-wrapper': {
      position: 'relative',
      width: '100%',
      paddingBottom: '56.25%',
      my: '8px',
      borderRadius: '6px',
      overflow: 'hidden',
      bgcolor: 'rgba(0,0,0,0.3)',
      '& iframe, & video': {
        position: 'absolute',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        border: 'none',
        borderRadius: '6px',
      },
    },
    '& video': {
      maxWidth: '100%',
      borderRadius: '6px',
      my: '8px',
    },
    '&:empty::before': {
      content: '"Start typing..."',
      color: vars.text3,
      fontStyle: 'italic',
    },
  },
}
