import { vars } from '~/theme'

export const styles = {
  'kanban-column': {
    flex: 1,
    minWidth: 260,
    display: 'flex',
    flexDirection: 'column',
    maxHeight: '100%',
  },
  'kanban-column__status-bar': {
    height: 3,
    borderRadius: '2px',
    mb: '12px',
    flexShrink: 0,
  },
  'kanban-column__header': {
    display: 'flex',
    alignItems: 'center',
    px: '4px',
    pb: '10px',
    gap: '8px',
    flexShrink: 0,
  },
  'kanban-column__title': {
    fontFamily: vars.ts,
    fontSize: 15,
    letterSpacing: '0.05em',
    flex: 1,
  },
  'kanban-column__count': {
    fontFamily: vars.mono,
    fontSize: 10,
    py: '2px',
    px: '7px',
    borderRadius: '4px',
  },
  'kanban-column__add': {
    width: 22,
    height: 22,
    borderRadius: '4px',
    bgcolor: 'transparent',
    border: `1px solid ${vars.border}`,
    color: vars.text3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: 14,
    transition: 'all 0.12s',
    flexShrink: 0,
    '&:hover': { borderColor: vars.borderHi, color: vars.text2 },
  },
  'kanban-column__cards': {
    flex: 1,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    p: '2px',
  },
}
