import { vars } from '~/theme'

export const styles = {
  'mod-card': {
    bgcolor: vars.card,
    border: `1px solid ${vars.border}`,
    borderRadius: '10px',
    overflow: 'hidden',
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    '&:hover': {
      borderColor: vars.borderHi,
      transform: 'translateY(-2px)',
      boxShadow: '0 8px 32px rgba(0,0,0,0.45)',
      '& .card-img': { transform: 'scale(1.05)' },
    },
  },
  'card-img-wrap': {
    position: 'relative',
    overflow: 'hidden',
    height: 190,
    flexShrink: 0,
  },
  'card-img-wrap--small': {
    position: 'relative',
    overflow: 'hidden',
    height: 120,
    flexShrink: 0,
  },
  'card-img': {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
    transition: 'transform 0.35s ease',
  },
  'card-img-placeholder': {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 42,
    background: `linear-gradient(135deg, ${vars.surface}, ${vars.cardHi})`,
  },
  'card-img-overlay': {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(180deg, transparent 40%, rgba(23,23,27,0.9))',
    zIndex: 1,
    pointerEvents: 'none',
  },
  'card-badges': {
    position: 'absolute',
    top: 8,
    left: 8,
    right: 8,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    zIndex: 2,
  },
  'card-game-tag': {
    fontFamily: vars.mono,
    fontSize: 8,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    bgcolor: 'rgba(12,12,14,0.82)',
    backdropFilter: 'blur(6px)',
    border: `1px solid ${vars.borderHi}`,
    color: vars.text2,
    py: '2px',
    px: '7px',
    borderRadius: '3px',
  },
  'card-body': {
    p: '12px 14px',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
  },
  'card-name': {
    fontFamily: vars.ts,
    fontSize: 17,
    letterSpacing: '0.03em',
    color: vars.text,
    lineHeight: 1.05,
  },
  'card-desc': {
    fontSize: 11,
    fontWeight: 300,
    color: vars.text2,
    lineHeight: 1.5,
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    flex: 1,
  },
  'card-stats': {
    display: 'flex',
    gap: '10px',
    mt: '6px',
  },
  'card-stat': {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontFamily: vars.mono,
    fontSize: 10,
    color: vars.text2,
    '& span': { color: vars.text, fontWeight: 600 },
    '& svg': { width: 11, height: 11, opacity: 0.7, flexShrink: 0 },
  },
  'card-footer': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    p: '8px 14px',
    borderTop: `1px solid ${vars.border}`,
    bgcolor: 'rgba(0,0,0,0.12)',
  },
  'card-author': {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  'author-av': {
    width: 18,
    height: 18,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 8,
    fontWeight: 700,
    color: '#fff',
    flexShrink: 0,
  },
  'author-av--default': {
    background: `linear-gradient(135deg, ${vars.accent}, #dc2626)`,
  },
  'author-name': {
    fontSize: 10,
    color: vars.text3,
    fontWeight: 500,
  },
  'card-footer__ver': {
    fontFamily: vars.mono,
    fontSize: 9,
    fontWeight: 500,
    color: vars.accent,
  },
}
