import { vars } from '~/theme'

export const styles = {
  'overlay': {
    position: 'fixed',
    inset: 0,
    zIndex: 9999,
    bgcolor: vars.bg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    pointerEvents: 'none',
    overflow: 'hidden',
  },
  'flash': {
    position: 'absolute',
    inset: 0,
    opacity: 0,
    pointerEvents: 'none',
  },
  'ring': {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%,-50%) scale(0)',
    width: 120,
    height: 120,
    borderRadius: '50%',
    border: '3px solid rgba(249,115,22,0.9)',
    opacity: 0,
  },
  'letter-m': {
    fontFamily: vars.ts,
    fontSize: 'clamp(140px, 22vw, 280px)',
    lineHeight: 1,
    position: 'absolute',
    top: '50%',
    right: '50%',
    letterSpacing: '-0.02em',
    userSelect: 'none',
    willChange: 'transform, opacity',
    color: vars.text,
  },
  'letter-f': {
    fontFamily: vars.ts,
    fontSize: 'clamp(140px, 22vw, 280px)',
    lineHeight: 1,
    position: 'absolute',
    top: '50%',
    left: '50%',
    letterSpacing: '-0.02em',
    userSelect: 'none',
    willChange: 'transform, opacity',
    color: vars.accent,
  },
}
