export const styles = {
  'header': { bgcolor: 'background.paper' },
  'header__nav-item': {
    boxShadow: '0 0 20px rgba(0,0,0,0.5)',
    height: 64,
    px: 1.5,
    transform: 'skew(-25deg, 0deg)',
  },
  'header__brand-text': {
    fontFamily: 'ThunderStrike',
    fontSize: 40,
    transform: 'skew(25deg, 0deg)',
  },
  'header__nav-text': {
    fontSize: 20,
    transform: 'skew(25deg, 0deg)',
  },
  'header__spacer': { flex: 1 },
  'header__actions': { display: 'flex', alignItems: 'center' },
  'header__donate': {
    backgroundColor: 'rgba(255, 215, 0, 0.25)',
    boxShadow: '0 0 20px rgba(0,0,0,0.5)',
    height: 64,
    px: 2,
    transform: 'skew(-25deg, 0deg)',
  },
  'header__donate-text': {
    fontSize: 20,
    transform: 'skew(25deg, 0deg)',
  },
  'header__avatar-container': {
    alignItems: 'center',
    display: 'flex',
    px: 1,
    transform: 'skew(-25deg, 0deg)',
  },
  'header__avatar': {
    cursor: 'pointer',
    height: 36,
    transform: 'skew(25deg, 0deg)',
    width: 36,
  },
  'header__login': {
    boxShadow: '0 0 20px rgba(0,0,0,0.75)',
    height: 64,
    transform: 'skew(-25deg, 0deg)',
  },
  'header__login-btn': {
    backgroundColor: '#5865F2',
    height: '100%',
    px: 3,
    transform: 'skew(25deg, 0deg)',
    '&:hover': { backgroundColor: '#4752c4' },
  },
  'header__login-text': {
    color: 'white',
    fontWeight: 'bold',
    transform: 'skew(25deg, 0deg)',
  },
  'header__menu-paper': {
    '& .MuiAvatar-root': { height: 32, ml: -0.5, mr: 1, width: 32 },
    '&:before': {
      bgcolor: 'background.paper',
      content: '""',
      display: 'block',
      height: 10,
      position: 'absolute',
      right: 23,
      top: 0,
      transform: 'translateY(-50%) rotate(45deg)',
      width: 10,
      zIndex: 0,
    },
    filter: 'drop-shadow(0px 2px 8px rgba(0,0,0,0.32))',
    mt: 1.5,
    overflow: 'visible',
    width: 180,
  },
}
