import { vars } from '~/theme'

export const styles = {
  'header': {
    display: 'flex',
    alignItems: 'center',
    height: 52,
    bgcolor: vars.nav,
    borderBottom: `1px solid ${vars.border}`,
    px: '20px',
    position: 'sticky',
    top: 0,
    zIndex: (theme) => theme.zIndex.drawer + 1,
  },
  'header__logo': {
    display: 'flex',
    alignItems: 'baseline',
    mr: '20px',
    cursor: 'pointer',
    lineHeight: 1,
    fontStyle: 'italic',
  },
  // Logo base styles
  'header__logo-lg': {
    fontFamily: vars.ts,
    fontSize: 30,
    letterSpacing: '-0.02em',
    textTransform: 'uppercase',
    lineHeight: 1,
    fontStyle: 'inherit',
  },
  'header__logo-sm': {
    fontFamily: vars.ts,
    fontSize: 22,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    lineHeight: 1,
    fontStyle: 'inherit',
  },
  // Logo color modifiers
  'header__logo--white': { color: vars.text },
  'header__logo--blue': { color: vars.modBlue },
  'header__logo--orange': { color: vars.accent },
  'header__nav': {
    display: 'flex',
    alignItems: 'stretch',
    height: '100%',
  },
  'header__nav-item': {
    display: 'flex',
    alignItems: 'center',
    px: '18px',
    fontSize: 13,
    fontWeight: 500,
    fontFamily: vars.ui,
    color: vars.text2,
    cursor: 'pointer',
    borderRight: `1px solid ${vars.border}`,
    transition: 'all 0.15s',
    '&:hover': { color: vars.text, bgcolor: 'rgba(255,255,255,0.02)' },
  },
  'header__right': {
    ml: 'auto',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  'header__donate-btn': {
    py: '6px',
    px: '16px',
    bgcolor: vars.donateBg,
    color: vars.donateText,
    fontSize: 12,
    fontWeight: 700,
    fontFamily: vars.ui,
    border: 'none',
    borderRadius: '3px',
    cursor: 'pointer',
    transition: 'all 0.15s',
    '&:hover': { bgcolor: vars.donateBgHover },
  },
  'header__avatar-wrap': {
    position: 'relative',
  },
  'header__avatar': {
    width: 32,
    height: 32,
    borderRadius: '50%',
    border: `2px solid ${vars.borderHi}`,
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 700,
  },
  'header__login-btn': {
    py: '6px',
    px: '16px',
    bgcolor: '#5865f2',
    color: '#fff',
    fontSize: 12,
    fontWeight: 700,
    fontFamily: vars.ui,
    border: 'none',
    borderRadius: '3px',
    cursor: 'pointer',
    transition: 'all 0.15s',
    textDecoration: 'none',
    '&:hover': { bgcolor: '#4752c4' },
  },
  'header__menu-paper': {
    '& .MuiAvatar-root': { height: 32, ml: -0.5, mr: 1, width: 32 },
    '&:before': {
      bgcolor: vars.surface,
      content: '""',
      display: 'block',
      height: 10,
      position: 'absolute',
      right: 23,
      top: 0,
      transform: 'translateY(-50%) rotate(45deg)',
      width: 10,
      zIndex: 0,
    },
    filter: 'drop-shadow(0px 2px 8px rgba(0,0,0,0.32))',
    mt: 1.5,
    overflow: 'visible',
    width: 180,
  },

  // -- Mode indicator --
  'header__mode-indicator': {
    display: 'flex',
    alignItems: 'center',
    gap: '7px',
    py: '5px',
    px: '12px',
    borderRadius: '5px',
    fontSize: 11,
    fontWeight: 700,
    fontFamily: vars.ui,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    transition: 'all 0.15s',
    border: '1px solid transparent',
    mx: 'auto',
  },
  'header__mode-indicator--mod': {
    bgcolor: vars.modBg,
    color: vars.modBlue,
    borderColor: vars.modBorder,
    '&:hover': { bgcolor: vars.modBgHover },
  },
  'header__mode-indicator--forge': {
    bgcolor: vars.accLo,
    color: vars.accent,
    borderColor: vars.accMed,
    '&:hover': { bgcolor: vars.accMed },
  },
  'header__mode-switch': {
    ml: '6px',
    fontSize: 10,
    opacity: 0.6,
  },

  // -- Search pill --
  'header__search-pill': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    bgcolor: vars.surface,
    border: `1px solid ${vars.border}`,
    borderRadius: '6px',
    py: '5px',
    px: '12px',
    fontSize: 12,
    color: vars.text3,
    fontFamily: vars.ui,
    width: 200,
    cursor: 'text',
    transition: 'all 0.15s',
    '&:hover': { borderColor: vars.borderHi, color: vars.text2 },
  },
  'header__search-icon': {
    fontSize: 13,
  },
  'header__search-key': {
    fontFamily: vars.mono,
    fontSize: 9,
    bgcolor: 'rgba(255,255,255,0.05)',
    border: `1px solid ${vars.borderHi}`,
    py: '1px',
    px: '5px',
    borderRadius: '3px',
    ml: 'auto',
  },
}
