import { vars } from '~/theme'

export const styles = {
  'main': {
    display: 'grid',
    gridTemplateRows: '52px 1fr',
    gridTemplateColumns: '220px 1fr',
    height: '100vh',
    overflow: 'hidden',
  },
  'main__header': {
    gridColumn: '1 / -1',
  },
  'main__content': {
    position: 'relative',
    minHeight: 0,
    overflow: 'hidden',
  },
  'main__scroll': {
    display: 'flex',
    flexDirection: 'column',
    overflowY: 'auto',
    height: '100%',
    position: 'relative',
    zIndex: 1,
  },

  // Topbar
  'main__topbar': {
    display: 'flex',
    alignItems: 'center',
    gap: 0,
    height: 52,
    borderBottom: `1px solid ${vars.border}`,
    flexShrink: 0,
    px: '24px',
    position: 'relative',
    zIndex: 1,
  },
  'main__breadcrumb': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: 13,
    color: vars.text2,
    flex: 1,
  },
  'main__bc-sep': {
    color: vars.text3,
  },
  'main__bc-active': {
    color: vars.text,
    fontWeight: 600,
  },
  'main__topbar-actions': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  'main__btn-ghost': {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    py: '6px',
    px: '14px',
    borderRadius: '6px',
    fontSize: 12,
    fontWeight: 600,
    fontFamily: vars.ui,
    cursor: 'pointer',
    transition: 'all 0.15s',
    bgcolor: 'transparent',
    border: `1px solid ${vars.borderHi}`,
    color: vars.text2,
    '&:hover': { bgcolor: 'rgba(255,255,255,0.04)', color: vars.text },
  },
  'main__btn-accent': {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    py: '6px',
    px: '14px',
    borderRadius: '6px',
    fontSize: 12,
    fontWeight: 700,
    fontFamily: vars.ui,
    cursor: 'pointer',
    transition: 'all 0.15s',
    bgcolor: vars.accent,
    color: '#000',
    border: 'none',
    '&:hover': { bgcolor: vars.accentHover, boxShadow: `0 4px 20px ${vars.accGlow}` },
  },

  // Metrics strip
  'main__metrics': {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    borderBottom: `1px solid ${vars.border}`,
    flexShrink: 0,
    position: 'relative',
    zIndex: 1,
  },
  'main__metric': {
    p: '18px 24px',
    borderRight: `1px solid ${vars.border}`,
    cursor: 'default',
    transition: 'background 0.15s',
    '&:last-child': { borderRight: 'none' },
    '&:hover': { bgcolor: 'rgba(255,255,255,0.012)' },
  },
  'main__metric-label': {
    fontFamily: vars.mono,
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    color: vars.text2,
    mb: '6px',
  },
  'main__metric-num': {
    fontFamily: vars.ts,
    fontSize: 36,
    letterSpacing: '0.03em',
    lineHeight: 1,
    color: vars.text,
    mb: '5px',
  },
  'main__metric-num--red': { color: vars.red },
  'main__metric-num--green': { color: vars.green },
  'main__metric-num--accent': { color: vars.accent },
  'main__metric-delta': {
    fontFamily: vars.mono,
    fontSize: 12,
    color: vars.green,
  },
  'main__metric-delta--neg': {
    fontFamily: vars.mono,
    fontSize: 12,
    color: vars.red,
  },
  'main__metric-delta--neu': {
    fontFamily: vars.mono,
    fontSize: 12,
    color: vars.text2,
  },
}
