import { vars } from '~/theme'

export const styles = {
  'sidenav': {
    bgcolor: vars.surface,
    borderRight: `1px solid ${vars.border}`,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    width: 220,
    flexShrink: 0,
  },

  // Project switcher
  'sn__project': {
    p: '14px 16px',
    borderBottom: `1px solid ${vars.border}`,
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    cursor: 'pointer',
    transition: 'background 0.15s',
    flexShrink: 0,
    '&:hover': { bgcolor: 'rgba(255,255,255,0.02)' },
  },
  'sn__proj-thumb': {
    width: 34,
    height: 34,
    borderRadius: '7px',
    flexShrink: 0,
    overflow: 'hidden',
    border: `1px solid ${vars.borderHi}`,
    bgcolor: vars.card,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 15,
  },
  'sn__proj-thumb-img': {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  'sn__proj-info': {
    flex: 1,
    minWidth: 0,
  },
  'sn__proj-name': {
    fontSize: 12,
    fontWeight: 700,
    color: vars.text,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  'sn__proj-ver': {
    fontFamily: vars.mono,
    fontSize: 9,
    color: vars.accent,
    mt: '1px',
  },
  'sn__chevron': {
    color: vars.text3,
    fontSize: 11,
    flexShrink: 0,
  },

  // Nav
  'sn__nav': {
    flex: 1,
    overflowY: 'auto',
    p: '10px 8px',
  },
  'sn__section': {
    fontFamily: vars.mono,
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: '0.14em',
    color: vars.text3,
    p: '6px 10px 8px',
  },
  'sn__item': {
    display: 'flex',
    alignItems: 'center',
    gap: '9px',
    py: '7px',
    px: '10px',
    borderRadius: '6px',
    mb: '1px',
    fontSize: 13,
    fontWeight: 500,
    color: vars.text2,
    cursor: 'pointer',
    transition: 'all 0.12s',
    '&:hover': { bgcolor: 'rgba(255,255,255,0.03)', color: vars.text },
  },
  'sn__item--active': {
    display: 'flex',
    alignItems: 'center',
    gap: '9px',
    py: '7px',
    px: '10px',
    borderRadius: '6px',
    mb: '1px',
    fontSize: 13,
    fontWeight: 500,
    color: vars.text,
    cursor: 'pointer',
    transition: 'all 0.12s',
    bgcolor: vars.accLo,
  },
  'sn__icon': {
    fontSize: 14,
    width: 16,
    textAlign: 'center',
    flexShrink: 0,
    opacity: 0.7,
  },
  'sn__icon--active': {
    fontSize: 14,
    width: 16,
    textAlign: 'center',
    flexShrink: 0,
    color: vars.accent,
  },
  'sn__badge': {
    ml: 'auto',
    fontFamily: vars.mono,
    fontSize: 9,
    py: '1px',
    px: '5px',
    borderRadius: '3px',
  },
  'sn__badge--red': {
    bgcolor: 'rgba(239,68,68,0.1)',
    border: '1px solid rgba(239,68,68,0.2)',
    color: '#f87171',
  },
  'sn__badge--accent': {
    bgcolor: vars.accLo,
    border: `1px solid ${vars.accMed}`,
    color: vars.accent,
  },
  'sn__badge--default': {
    bgcolor: 'rgba(255,255,255,0.05)',
    border: `1px solid ${vars.border}`,
    color: vars.text3,
  },
  'sn__divider': {
    height: '1px',
    bgcolor: vars.border,
    my: '8px',
  },

  // Footer
  'sn__footer': {
    borderTop: `1px solid ${vars.border}`,
    p: '10px 8px',
    flexShrink: 0,
  },
  'sn__user': {
    display: 'flex',
    alignItems: 'center',
    gap: '9px',
    py: '7px',
    px: '10px',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'background 0.12s',
    '&:hover': { bgcolor: 'rgba(255,255,255,0.03)' },
  },
  'sn__user-av': {
    width: 28,
    height: 28,
    borderRadius: '7px',
    background: `linear-gradient(135deg, ${vars.accent}, #dc2626)`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 11,
    fontWeight: 700,
    color: '#fff',
    flexShrink: 0,
    overflow: 'hidden',
  },
  'sn__user-av-img': {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  'sn__user-name': {
    fontSize: 12,
    fontWeight: 600,
    color: vars.text,
  },
  'sn__user-role': {
    fontSize: 10,
    color: vars.text3,
  },
  'sn__user-arrow': {
    ml: 'auto',
    color: vars.text3,
    fontSize: 11,
  },
}
