import { vars } from '~/theme'

export const styles = {
  'pcard': {
    display: 'grid',
    gridTemplateColumns: '64px 1fr',
    bgcolor: vars.card,
    border: `1px solid ${vars.border}`,
    borderRadius: '9px',
    overflow: 'hidden',
    cursor: 'pointer',
    transition: 'all 0.15s',
    position: 'relative',
    '&:hover': {
      bgcolor: vars.cardHi,
      borderColor: vars.borderHi,
      '&::before': { bgcolor: vars.accent },
    },
    '&::before': {
      content: '""',
      position: 'absolute',
      left: 0,
      top: 0,
      bottom: 0,
      width: '2px',
      bgcolor: 'transparent',
      transition: 'background 0.15s',
      borderRadius: '9px 0 0 9px',
    },
  },
  'pcard--live': {
    mb: '10px',
    borderColor: vars.accent,
    '&::before': { bgcolor: vars.green },
  },
  'pcard--beta': {
    '&::before': { bgcolor: vars.yellow },
  },
  'pcard-thumb': {
    width: 64,
    minHeight: 72,
    bgcolor: vars.surface,
    borderRight: `1px solid ${vars.border}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 24,
    flexShrink: 0,
    position: 'relative',
    zIndex: 1,
  },
  'pcard-body': {
    p: '10px 13px',
    position: 'relative',
    zIndex: 1,
  },
  'pcard-top': {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    mb: '2px',
  },
  'pcard-name': {
    fontSize: 13,
    fontWeight: 700,
    color: vars.text,
  },
  'pcard-tag': {
    fontFamily: vars.mono,
    fontSize: 8,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    color: vars.text2,
    bgcolor: 'rgba(255,255,255,0.04)',
    border: `1px solid ${vars.borderHi}`,
    py: '1px',
    px: '5px',
    borderRadius: '3px',
  },
  'pcard-desc': {
    fontSize: 11,
    fontWeight: 400,
    color: vars.text2,
    lineHeight: 1.4,
    display: '-webkit-box',
    WebkitLineClamp: 1,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    mb: '6px',
  },
  'pcard-pills': {
    display: 'flex',
    gap: '4px',
    flexWrap: 'wrap',
  },
  'pp': {
    fontFamily: vars.mono,
    fontSize: 9,
    py: '2px',
    px: '6px',
    borderRadius: '3px',
    border: `1px solid ${vars.borderHi}`,
    bgcolor: 'rgba(255,255,255,0.05)',
    color: vars.text2,
  },
  'pp--bug': {
    bgcolor: 'rgba(239,68,68,0.08)',
    borderColor: 'rgba(239,68,68,0.18)',
    color: '#f87171',
  },
  'pp--ok': {
    bgcolor: 'rgba(34,197,94,0.07)',
    borderColor: 'rgba(34,197,94,0.15)',
    color: '#4ade80',
  },
  'pcard-caret': {
    position: 'absolute',
    right: 0,
    top: '50%',
    transform: 'translateY(-50%)',
    zIndex: 2,
    width: '22px',
    height: '36px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    bgcolor: vars.accent,
    color: '#000',
    border: 'none',
    borderRadius: '4px 0 0 4px',
    fontSize: 18,
    fontWeight: 700,
    cursor: 'pointer',
    fontFamily: vars.ui,
    transition: 'width 0.15s, background 0.15s',
    '&:hover': {
      width: '26px',
      bgcolor: vars.accentHover,
    },
  },
  'sdot': {
    width: 7,
    height: 7,
    borderRadius: '50%',
  },
  'sd-live': { bgcolor: vars.green, boxShadow: `0 0 5px ${vars.green}` },
  'sd-beta': { bgcolor: vars.yellow, boxShadow: `0 0 5px ${vars.yellow}` },
  'sd-grey': { bgcolor: vars.text3 },
  'pcard-prog': {
    position: 'absolute',
    bottom: 0,
    left: 64,
    right: 0,
    height: '2px',
    bgcolor: 'rgba(255,255,255,0.03)',
  },
  'pcard-prog-fill': {
    height: '100%',
    opacity: 0.5,
    borderRadius: '0 2px 2px 0',
  },
  'pcard-prog-fill--accent': { bgcolor: vars.accent },
  'pcard-prog-fill--yellow': { bgcolor: vars.yellow },
  'pcard-prog-fill--green': { bgcolor: vars.green },
  'pcard-game-icon-wrap': {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    overflow: 'hidden',
    pointerEvents: 'none',
    zIndex: 0,
  },
  'pcard-game-icon-inner': {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    pr: '12px',
  },
  'pcard-game-icon': {
    height: '75%',
    opacity: 0.09,
    filter: 'grayscale(0.3)',
    objectFit: 'contain',
  },
}
