import { vars } from '~/theme'

export const styles = {
  // -- Layout --
  'pp': {
    display: 'grid',
    gridTemplateColumns: '1fr 300px',
    flex: 1,
    minHeight: 0,
    position: 'relative',
    zIndex: 1,
  },
  'pp__left': {
    p: '24px 28px',
    borderRight: `1px solid ${vars.border}`,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '28px',
  },
  'pp__top-row': {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '20px',
    alignItems: 'stretch',
  },
  'pp__bottom-row': {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '20px',
    alignItems: 'start',
    flex: 1,
  },
  'pp__right': {
    p: '20px 18px',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    overflowY: 'auto',
    overflowX: 'hidden',
  },

  // -- Hero card --
  'pp-hero': {
    bgcolor: vars.card,
    border: `1px solid ${vars.border}`,
    borderRadius: '12px',
    overflow: 'hidden',
  },
  'pp-hero__banner': {
    height: 140,
    position: 'relative',
    overflow: 'hidden',
    background: `linear-gradient(140deg, ${vars.bannerStart} 0%, ${vars.bannerMid} 50%, ${vars.bannerEnd} 100%)`,
  },
  'pp-hero__banner-img': {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  'pp-hero__banner-glow': {
    position: 'absolute',
    inset: 0,
    background: `radial-gradient(ellipse at 30% 60%, ${vars.accGlow}, transparent 60%), radial-gradient(ellipse at 70% 30%, ${vars.blueGlow}, transparent 50%)`,
  },
  'pp-hero__banner-accent': {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '2px',
    background: `linear-gradient(90deg, ${vars.accent}, transparent)`,
  },
  'pp-hero__body': {
    p: '20px 24px 24px',
  },

  // Title row
  'pp-hero__title-row': {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '14px',
    mb: '10px',
  },
  'pp-hero__avatar': {
    width: 52,
    height: 52,
    borderRadius: '10px',
    border: `2px solid ${vars.borderHi}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 22,
    flexShrink: 0,
    mt: '-38px',
    position: 'relative',
    zIndex: 2,
    boxShadow: `0 4px 16px ${vars.shadow}`,
    overflow: 'hidden',
    bgcolor: vars.surface,
  },
  'pp-hero__avatar-img': {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  'pp-hero__title-info': {
    flex: 1,
    pt: '4px',
  },
  'pp-hero__name': {
    fontFamily: vars.ts,
    fontSize: 26,
    letterSpacing: '0.04em',
    color: vars.text,
    lineHeight: 1,
    mb: '6px',
  },
  'pp-hero__meta-row': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
  },
  'pp-hero__version-badge': {
    fontFamily: vars.mono,
    fontSize: 10,
    bgcolor: vars.accLo,
    border: `1px solid ${vars.accMed}`,
    color: vars.accent,
    py: '2px',
    px: '8px',
    borderRadius: '4px',
    fontWeight: 500,
  },
  'pp-hero__status-pill': {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    fontFamily: vars.mono,
    fontSize: 9,
    py: '2px',
    px: '8px',
    borderRadius: '4px',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  'pp-hero__status-pill--public': {
    bgcolor: vars.greenLo,
    border: `1px solid ${vars.greenMed}`,
    color: vars.green,
  },
  'pp-hero__status-pill--private': {
    bgcolor: vars.accLo,
    border: `1px solid ${vars.accMed}`,
    color: vars.accent,
  },
  'pp-hero__status-dot': {
    width: 5,
    height: 5,
    borderRadius: '50%',
    bgcolor: 'currentColor',
  },
  'pp-hero__history-button': {
    width: 26,
    height: 26,
    borderRadius: '5px',
    bgcolor: 'transparent',
    border: `1px solid ${vars.border}`,
    color: vars.text3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: 13,
    transition: 'all 0.12s',
    ml: '2px',
    '&:hover': { borderColor: vars.borderHi, color: vars.text2 },
  },

  // Owner
  'pp-hero__owner-row': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    mb: '16px',
  },
  'pp-hero__owner-avatar': {
    width: 22,
    height: 22,
    borderRadius: '5px',
    background: vars.discordGradient,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 9,
    fontWeight: 700,
    color: '#fff',
    overflow: 'hidden',
  },
  'pp-hero__owner-avatar-img': {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  'pp-hero__owner-name': {
    fontSize: 12,
    fontWeight: 600,
    color: vars.text2,
  },

  // Description
  'pp-hero__description': {
    fontSize: 13,
    fontWeight: 300,
    color: vars.text2,
    lineHeight: 1.65,
    mb: '16px',
  },

  // Stats row
  'pp-hero__stats-row': {
    display: 'flex',
    alignItems: 'center',
    gap: 0,
    pt: '14px',
    borderTop: `1px solid ${vars.border}`,
  },
  'pp-hero__stat': {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    px: '18px',
    borderRight: `1px solid ${vars.border}`,
    fontSize: 12,
    color: vars.text2,
    '&:first-of-type': { pl: 0 },
    '&:last-of-type': { borderRight: 'none' },
  },
  'pp-hero__stat-icon': {
    fontSize: 13,
    color: vars.text3,
  },
  'pp-hero__stat-value': {
    fontFamily: vars.mono,
    fontSize: 11,
    color: vars.text,
    fontWeight: 500,
  },
  'pp-hero__stat-label': {
    fontSize: 11,
    color: vars.text3,
  },

  // -- Section header --
  'pp-section__head': {
    display: 'flex',
    alignItems: 'center',
    mb: '14px',
  },
  'pp-section__title': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: 12,
    fontWeight: 700,
    color: vars.text,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  'pp-section__count': {
    fontFamily: vars.mono,
    fontSize: 9,
    bgcolor: vars.pillBg,
    border: `1px solid ${vars.border}`,
    py: '1px',
    px: '6px',
    borderRadius: '3px',
    color: vars.text3,
  },
  'pp-section__action': {
    fontSize: 11,
    fontWeight: 600,
    color: vars.accent,
    cursor: 'pointer',
    py: '3px',
    px: '8px',
    borderRadius: '4px',
    border: `1px solid ${vars.accMed}`,
    bgcolor: vars.accLo,
    transition: 'all 0.12s',
    '&:hover': { bgcolor: vars.accLoHover },
  },

  // -- Members --
  'pp-member__wrapper': {
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
  },
  'pp-member': {
    bgcolor: vars.surface,
    border: `1px solid ${vars.border}`,
    borderRadius: '9px',
    p: '14px 16px',
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
  },
  'pp-member__list': {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 26px 1fr auto)',
    gap: '6px 12px',
  },
  'pp-member__row': {
    display: 'grid',
    gridTemplateColumns: 'subgrid',
    gridColumn: 'span 3',
    alignItems: 'center',
    py: '6px',
    px: '8px',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'background 0.12s',
    '&:hover': { bgcolor: vars.hoverBg },
    minWidth: 0,
  },
  'pp-member__avatar': {
    width: 26,
    height: 26,
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 10,
    fontWeight: 700,
    color: '#fff',
    flexShrink: 0,
    overflow: 'hidden',
  },
  'pp-member__avatar-img': {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  'pp-member__name': {
    fontSize: 12,
    fontWeight: 600,
    color: vars.text,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  'pp-member__role': {
    fontFamily: vars.mono,
    fontSize: 8,
    py: '1px',
    px: '5px',
    borderRadius: '3px',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    textAlign: 'center',
  },
  'pp-member__role--owner': {
    bgcolor: vars.greenLo,
    border: `1px solid ${vars.greenMed}`,
    color: vars.green,
  },
  'pp-member__role--maintainer': {
    bgcolor: vars.accLo,
    border: `1px solid ${vars.accMed}`,
    color: vars.accent,
  },
  'pp-member__role--contributor': {
    bgcolor: vars.blueLo,
    border: `1px solid ${vars.blueMed}`,
    color: vars.blue,
  },

  // -- Categories --
  'pp-category__grid': {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  'pp-category': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    bgcolor: vars.card,
    border: `1px solid ${vars.border}`,
    borderRadius: '8px',
    py: '8px',
    px: '14px',
    cursor: 'pointer',
    transition: 'all 0.15s',
    position: 'relative',
    overflow: 'hidden',
    '&:hover': { borderColor: vars.borderHi, bgcolor: vars.cardHi },
  },
  'pp-category__dot': {
    width: 7,
    height: 7,
    borderRadius: '50%',
    flexShrink: 0,
  },
  'pp-category__name': {
    fontSize: 12,
    fontWeight: 600,
    color: vars.text,
  },
  'pp-category__progress': {
    fontFamily: vars.mono,
    fontSize: 10,
    color: vars.text3,
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
  },
  'pp-category__bar': {
    width: 40,
    height: 3,
    bgcolor: vars.progressBg,
    borderRadius: '2px',
    overflow: 'hidden',
  },
  'pp-category__fill': {
    height: '100%',
    borderRadius: '2px',
  },
  'pp-category__progress-line': {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '2px',
    bgcolor: vars.progressBg,
  },
  'pp-category__progress-line-fill': {
    height: '100%',
    borderRadius: '0 2px 2px 0',
    opacity: 0.6,
  },

  // -- Right panel widgets --
  'pp-widget__label': {
    fontFamily: vars.mono,
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: '0.14em',
    color: vars.text3,
    mb: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  'pp-widget__link': {
    color: vars.text3,
    cursor: 'pointer',
    fontSize: 9,
    transition: 'color 0.12s',
    '&:hover': { color: vars.accent },
  },

  // Info rows
  'pp-info__rows': {
    display: 'flex',
    flexDirection: 'column',
  },
  'pp-info__row': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    py: '9px',
    borderBottom: `1px solid ${vars.border}`,
    fontSize: 12,
    '&:last-of-type': { borderBottom: 'none' },
  },
  'pp-info__key': {
    color: vars.text3,
    fontWeight: 400,
  },
  'pp-info__value': {
    color: vars.text2,
    fontWeight: 500,
    fontFamily: vars.mono,
    fontSize: 11,
  },
  'pp-info__value--accent': {
    color: vars.accent,
  },
  'pp-info__value--green': {
    color: vars.green,
  },

}
